FROM python:3.9-slim
WORKDIR /app
ENV AUTORIZADOR_HOST="http://ec2-52-207-65-64.compute-1.amazonaws.com"
ENV SERVICE_PORT="6002"
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app.py .
CMD ["python", "app.py"]